// File generated by FlutterFire CLI — DO NOT EDIT MANUALLY.
// This is a placeholder. Run `flutterfire configure` to generate the real file.
//
// To generate:
//   1. Install Firebase CLI:   npm install -g firebase-tools
//   2. Install FlutterFire CLI: dart pub global activate flutterfire_cli
//   3. Run:                     flutterfire configure --project=teranga-events-dev
//
// See: https://firebase.google.com/docs/flutter/setup

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not configured for this platform. '
          'Run `flutterfire configure` to generate platform-specific options.',
        );
    }
  }

  // TODO: Replace with actual values from `flutterfire configure`
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'YOUR-ANDROID-API-KEY',
    appId: '1:000000000000:android:0000000000000000000000',
    messagingSenderId: '000000000000',
    projectId: 'teranga-events-dev',
    storageBucket: 'teranga-events-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR-IOS-API-KEY',
    appId: '1:000000000000:ios:0000000000000000000000',
    messagingSenderId: '000000000000',
    projectId: 'teranga-events-dev',
    storageBucket: 'teranga-events-dev.appspot.com',
    iosBundleId: 'com.teranga.events',
  );
}
